authors:
  boegel:
    name: Kenneth Hoste
    description: HPC-UGent
    avatar: https://avatars.githubusercontent.com/u/620876?v=4
    slug: https://github.com/boegel
  branfosj:
    name: Simon Branford
    description: University of Birmingham
    avatar: https://avatars.githubusercontent.com/u/4967?v=4
    slug: https://github.com/branfosj
  hvelab:
    name: Helena Vela Beltran
    description: Do IT Now
    avatar: https://avatars.githubusercontent.com/u/47674829?v=4
    slug: https://github.com/hvelab
