authors:
  boegel:
    name: Kenneth Hoste
    description: HPC-UGent
    avatar: https://avatars.githubusercontent.com/u/620876?v=4
    slug: https://github.com/boegel
  hvelab:
    name: Helena Vela Beltran
    description: Do IT Now
    avatar: https://avatars.githubusercontent.com/u/47674829?v=4
    slug: https://github.com/hvelab
  lexming:
    name: Alex Domingo
    description: Vrije Universiteit Brussel
    avatar: https://avatars.githubusercontent.com/u/4973794?v=4
    slug: https://github.com/lexming
