# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: build blog
on: [push, pull_request]
# Declare default permissions as read only.
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: set up Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: '3.12'

    - name: Codespell action
      uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630 # v2.1
      with:
        check_filenames: true
        skip: '*.pdf,.git,*.json'
        ignore_words_list: 

    - name: install mkdocs + plugins
      run: |
          pip install -r requirements.txt
          pip list | grep mkdocs
          mkdocs --version

    - name: build blog
      run: make test
