# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: build blog
on: [push, pull_request]
# Declare default permissions as read only.
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0

    - name: set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.12'

    - name: Codespell action
      uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2
      with:
        check_filenames: true
        skip: '*.pdf,.git,*.json,*.js,*.css'
        ignore_words_list: AKS,aks,BASF,basf

    - name: install mkdocs + plugins
      run: |
          pip install -r requirements.txt
          pip list | grep mkdocs
          mkdocs --version

    - name: build blog
      run: make test
